const String baseurl = "https://pos.vantura.id/api/";
const String emailCheck ="/auth/checkemail?email=";
const String phoneNumberCheck ="/auth/checkphone?phone=";
const String usernameCheck ="/auth/checkusername?username=";
const String imageUrl = "https://pos.vantura.id/images/";
const String login = "auth/login";
const String register = "auth/register";
const String todayspick = "product/todaypick";
const String category = "category";
const String getProduct1 = "category/product/all?outlet_id=2";
const String getProduct2 = "category/product/1?outlet_id=2";
const String gopay = "https://api.sandbox.midtrans.com/v2/charge";
const String google = "https://people.googleapis.com/v1/people/me/connections?requestMask.includeField=person.names"; 